
# 应用服务 WEB 访问端口
server:
  port: 80



spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://106.52.174.44:3306/PM?characterEncoding=utf-8&allowMultiQueries=true
      username: root
      password: 123456
  application:
    name: springthf
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    username: 351659704@qq.com
    password: fzywtxfyneeecbea
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: ture
  redis:
    database: 0
    host: 106.52.174.44
    port: 6379
    password: 123456
    timeout: 100000
    jedis:
      pool:
        max-active: 8
        max-wait: 8000
        max-idle: 8
        min-idle: 0
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    cache: false
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.thf.entity



#
#  spring
#    mail.default-encoding=UTF-8
#  spring.mail.host=smtp.qq.com
#  spring.mail.username=你的邮箱
#  spring.mail.password=邮箱授权码
#  spring.mail.properties.mail.smtp.auth=true
#  spring.mail.properties.mail.smtp.starttls.enable=true

